# Utiliza una imagen base de Python
FROM python:3.9

# Configuraciones del contenedor
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Directorio de trabajo
WORKDIR /code

# Instalación de las dependencias del proyecto
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# Copia de los archivos del proyecto al contenedor
COPY . /code/
