# Generated by Django 3.2.13 on 2023-02-16 22:17

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('date_update', models.DateField(auto_now=True, verbose_name='fecha de Modificacion')),
                ('date_delate', models.DateField(auto_now=True, verbose_name='fecha de Eliminacion')),
                ('name_author', models.CharField(max_length=50, verbose_name='Nombre del Autor')),
                ('last_name_author', models.CharField(max_length=50, verbose_name='Nombre del Autor')),
                ('date_born_author', models.DateField(verbose_name='Fecha de Nacimiento del Autor')),
                ('date_dead_author', models.DateField(verbose_name='Fecha de Fallecimiento del Autor')),
                ('nationality_author', django_countries.fields.CountryField(max_length=2, verbose_name='Nacionalidad del Autor')),
                ('biography_author', ckeditor.fields.RichTextField(verbose_name='Bibliografía del Autor')),
                ('image_author', models.ImageField(upload_to='autor', verbose_name='Imagen del Autor')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
