# Generated by Django 3.2.13 on 2023-02-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='type_archive',
            new_name='archive',
        ),
    ]
